AllowedHosts = "*"

[Serilog]
Using = [
  "Serilog.Sinks.Console",
  "Me.Xfox.ZhuiAnime",
  "Sentry.Serilog",
  "Serilog.Sinks.Grafana.Loki",
]

[Serilog.MinimumLevel]
Default = "Debug"
[Serilog.MinimumLevel.Override]
Microsoft = "Information"
"Microsoft.AspNetCore" = "Warning"
"Microsoft.EntityFrameworkCore.Database.Command" = "Warning"
"AspNetCore.SpaYarp" = "Information"
"Yarp.ReverseProxy" = "Warning"

[Serilog.WriteTo.Console]
Name = "Console"

[Serilog.Properties]
Application = "ZhuiAni.me"

[ConnectionStrings]
ZAContext = "Host=localhost;Database=zhuianime;Include Error Detail=true"

[Modules.TorrentDirectory]
IntervalBetweenFetch = 00:05:00
IntervalBetweenPages = 00:00:10
FetchPageThreshold = 20

[Modules.TorrentDirectory.Sources]
"bangumi.moe" = true
"acg.rip" = true

[Modules.PikPak]
Username = ""
Password = ""
AccessAddressTemplate = "{0}"
IntervalBetweenFetch = 01:00:00

# See https://developers.cloudflare.com/turnstile/
[Captcha]
Enabled = true
SiteKey = ""
Secret = ""

[Authentication.Jwt]
# Generate ECC key with https://dinochiesa.github.io/jwt/
PrivateKey = """
-----BEGIN PRIVATE KEY-----
......
-----END PRIVATE KEY-----
"""
PublicKey = """
-----BEGIN PUBLIC KEY-----
......
-----END PUBLIC KEY-----
"""
Issuer = "https://zhuiani.me"
AudienceFirstParty = "https://zhuiani.me"
FirstPartyExpires = 00:10:00
RefreshExpiresDays = 7
